### ISSUE TITLE
Since latest update, calibre runs, but connection not working

### ISSUE THREAD

**Issue by maxximux2000** [linuxserver/docker-calibre#104]
I have multiples docker containers on the same server that are all working exept Calibre since the latest update. I get a connection refused by server, I check the docker container status in Portainer.IO and it's working as expected, but I cannot connect from the server itself using localhost or from another computer on the same network using the server ip:8080. I tried multiples browser as well (Chrome and Firefox) with same result. Server is Ubuntu 22.04.1 LTS

**Comment by aptalca** [comment]
You probably have locally cached image of a 6.5.0 version that was pushed before the rebase to jammy. Do a docker pull and recreate, it will likely no longer work.

Make sure you add the seccomp arg that's now in the readme

**Comment by dangmai** [comment]
Good point about it being locally cached! I will have to figure out a way to add the seccomp profile to a Kubernetes pod then, since it's not even running Docker (it's running containerd). Hopefully there is a way around it.

**Comment by aptalca** [comment]
Pretty sure k8s supports security options. Let us know if it works because there are too many users reporting similar issues with little to no confirmation of whether that solved their issue

**Comment by dangmai** [comment]
Yeah same here, `Unconfined` seccomp policy does not help.

**Comment by maxximux2000** [comment]
I have personally downgraded to version 6.4.0 and now I can access the calibre library without problem, I will continue to monitor the new release to see if this has been resolved.

**Comment by j0nnymoe** [comment]
Multiple reasons why you could be having issues here. Unless people provide information about their deployment and hardware/os they're using, we can't help. (Hence why this issue is marked as invalid)

**Comment by aptalca** [comment]
What's your compose yaml?

**Comment by PriamX** [comment]
@aptalca FYI...

```
 calibre:
    image: linuxserver/calibre
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Denver
      - SUBFOLDER=/calibre/
    volumes:
      - /media/docker/appdata/calibre:/config
      - /media/books/calibre/library:/books
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - mynet
    healthcheck:
      test: (curl --fail -s http://localhost:8080/ && curl --fail -s http://localhost:8081/) || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
```
