### ISSUE TITLE
Docker container fails to start for any release after 6.4.0

### ISSUE THREAD

**Issue by sjthespian** [linuxserver/docker-calibre#105]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Docker container should run with no errors in the log

## Current Behavior
The container fails to start completely and the log is full of messages like the following:
```
s6-supervise custom-svc-README.txt (child): fatal: unable to exec run: Exec format error
s6-supervise custom-svc-README.txt: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise custom-svc-README.txt (child): fatal: unable to exec run: Exec format error
s6-supervise custom-svc-README.txt: warning: unable to spawn ./run - waiting 10 seconds
```

## Steps to Reproduce
1. Pull ghcr.io/linuxserver/calibre:latest
2. Start the container with a docker-compose block like the following:
```
  calibre:
    image: ghcr.io/linuxserver/calibre
    labels:
    - "com.centurylinklabs.watchtower.scope=plex"
    container_name: calibre
    networks:
    - plex
    environment:
    - UMASK_SET=002
    - TZ=America/Los_Angeles
    - DOCKER_MODS=linuxserver/mods:universal-package-install
    - INSTALL_PACKAGES=unzip|libui-dialog-perl|libterm-readline-gnu-perl
    ports:
    - 8082:8080/tcp
    - 8083:8081/tcp
    restart: unless-stopped
```

## Environment
**OS:** 20.04.5 LTS (Focal Fossa)
**CPU architecture:** x86_64
**How docker service was installed:** Official repo

## Command used to create docker container (run/create/compose/screenshot)

```yaml
  calibre:
    image: ghcr.io/linuxserver/calibre:6.4.0
    labels:
    - "com.centurylinklabs.watchtower.scope=plex"
    container_name: calibre
    networks:
    - plex
    environment:
    - PUID=10761
    - PGID=10765
    - UMASK_SET=002
    - TZ=America/Los_Angeles
    - DOCKER_MODS=linuxserver/mods:universal-package-install
    - INSTALL_PACKAGES=unzip|libui-dialog-perl|libterm-readline-gnu-perl
    volumes:
    - /opt/plex/calibre:/config
    - /srv/media/books/Calibre:/books
    - /srv/media/downloads:/downloads
    ports:
    - 8082:8080/tcp
    - 8083:8081/tcp
    restart: unless-stopped
```

## Docker logs

[docker-calibre-logs.txt](https://github.com/linuxserver/docker-calibre/files/9687454/docker-calibre-logs.txt)
