### ISSUE TITLE
Calibre not starting after latest update

### ISSUE THREAD

**Issue by lopiv2** [linuxserver/docker-calibre#115]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
When I create the docker, it is supposed to start the container in a right way.

## Current Behavior
Errors appears:
[_calibre_logs.txt](https://github.com/linuxserver/docker-calibre/files/9932159/_calibre_logs.txt)

## Steps to Reproduce

1. Executing Docker compose
2. 

## Environment
**OS: Ubuntu
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

Docker was installed from Repo, in Linux

## Command used to create docker container (run/create/compose/screenshot)

```
calibre:
    image: linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    volumes:
      - /books:/config
    ports:
      - 8091:8080 
      - 8082:8081
    restart: unless-stopped
    networks:
      - traefik_proxy
 ```
