### ISSUE TITLE
[BUG] Container hangs on start

### ISSUE THREAD

**Issue by createchange** [linuxserver/docker-calibre#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running `docker-compose up`, the container hangs. I was previously running 6.9.0, and then tried swapping over to 6.10.0. This failed. When reverting back to 6.9.0, RDP was no longer functioning. Unfortunately. I did not capture that error.

Now, the container simply won't start at all - it hangs as per the below log

```
$ docker-compose logs -f
Attaching to calibre_1
calibre_1  | [custom-init] No custom services found, skipping...
calibre_1  | [migrations] started
calibre_1  | [migrations] no migrations found
calibre_1  |
calibre_1  | -------------------------------------
calibre_1  |           _         ()
calibre_1  |          | |  ___   _    __
calibre_1  |          | | / __| | |  /  \
calibre_1  |          | | \__ \ | | | () |
calibre_1  |          |_| |___/ |_|  \__/
calibre_1  |
calibre_1  |
calibre_1  | Brought to you by linuxserver.io
calibre_1  | -------------------------------------
calibre_1  |
calibre_1  | To support LSIO projects visit:
calibre_1  | https://www.linuxserver.io/donate/
calibre_1  | -------------------------------------
calibre_1  | GID/UID
calibre_1  | -------------------------------------
calibre_1  |
calibre_1  | User uid:    1000
calibre_1  | User gid:    1000
calibre_1  | -------------------------------------
calibre_1  |
calibre_1  |
calibre_1  | Generating 2048 bit rsa key...
calibre_1  |
calibre_1  | ssl_gen_key_xrdp1 ok
calibre_1  |
calibre_1  | saving to rsakeys.ini
calibre_1  |
calibre_1  | ..+........+...............+......+......+.+..+......+.........+.......+.....+...+...+.......+......+..+.......+..+.+.....+....+.....+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+...+.....+....+..+..........+.....+...+..........+........+...+.+....................+.+...+..+.......+..+.+.....+...+.......+...+.........+..+....+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+...........+.....................................+......+.....+....+..+...+......+.........+.+......+........+.......+...+...+.....+.................................+.+......+...+......+.....+................+.........+..............+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
calibre_1  | ...+......+..+.+..............+..........+...+...+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+......+...+..+....+..+....+...+........+.........+....+.....+.........+.+......+........+......+.+......+..............+.+..+.+..............+...+..........+...+..+...+.+.....+...+.......+........+.+......+...+..+...+............+....+..+.........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+.+...+......+..+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
calibre_1  | -----
calibre_1  | **** Setting password from environment variable. ****
calibre_1  | [custom-init] No custom files found, skipping...
^CERROR: Aborting.
```

I have used `docker-compose down` to clean up, and also tried `docker system prune --all --volumes --force` to ensure that there is nothing cached.

I think it is very possible, maybe likely, that the issue is an issue with my server. However, I don't exactly know where to go from here, as the hanging doesn't really clue me into what might be occurring.

### Expected Behavior

Clean start of container, with the service being accessible.

### Steps To Reproduce

Not sure how to reproduce exactly...

1. In Ubuntu Server 22.04, install docker
2. Using following docker-compose file, bring service up:
```
version: '3.9'
services:
    calibre:
      image: lscr.io/linuxserver/calibre:6.9.0
      volumes:
          - /home/<redacted>/ebooks:/calibre
          - /home/<redacted>/ingest:/ingest
      network_mode: host
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/New_York
        - PASSWORD=<redacted>
      security_opt:
        - seccomp=unconfined
      restart: unless-stopped
      logging:
        options:
          max-size: "10m"
          max-file: "5"
```
3. Attempt to upgrade from 6.9.0 -> 6.10.0

### Environment

```markdown
- OS: Ubuntu

Linux ebooks 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
- How docker service was installed: apt
```
$ docker list --installed | grep docker-ce
docker-ce/jammy,now 5:20.10.22~3-0~ubuntu-jammy amd64 [installed]
```

### CPU architecture

x86-64

### Docker creation

```bash
See above
```

### Container logs

```bash
See above
```
