### ISSUE TITLE
[BUG] unable to start container since v6.15.0-ls211 

### ISSUE THREAD

**Issue by jrhbcn** [linuxserver/docker-calibre#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since version v6.15.0-ls211 I am unable to start the docker container. Logs show:

```
mv: cannot move '/usr/local/etc/kasmvnc/kasmvnc.yaml.lsio' to a subdirectory of itself, '/usr/local/etc/kasmvnc/kasmvnc.yaml'
s6-rc: warning: unable to start service init-kasmvnc-config: command exited 1
```

Previous version v6.15.0-ls210 runs fine.

### Expected Behavior

Container starts normally.

### Steps To Reproduce

1. Create docker compose entry
2. Start container
3. container start fails with error

### Environment

```markdown
- OS: LXC container on a proxmox 7.4 machine
- docker installed using standard docker instructions for debian bullseye
- Using recommended docker-compose options
```

### CPU architecture

x86-64

### Docker creation

```bash
docker compose up -d calibre
```

### Container logs

```bash
mv: cannot move '/usr/local/etc/kasmvnc/kasmvnc.yaml.lsio' to a subdirectory of itself, '/usr/local/etc/kasmvnc/kasmvnc.yaml'
s6-rc: warning: unable to start service init-kasmvnc-config: command exited 1
```

**Comment by Roxedus** [comment]
Post your compose

**Comment by jrhbcn** [comment]
This is my docker compose file:

```
  calibre:
    image: lscr.io/linuxserver/calibre
    container_name: calibre
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /mnt/downloads:/downloads
      - /mnt/media/ebooks:/books
      - ./data/calibre:/config

```
