### ISSUE TITLE
Support for arm64 architecture (raspberry pi)

### ISSUE THREAD

**Issue by ianpogi5** [linuxserver/docker-calibre#32]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Run on raspberry pi

## Current Behavior
Get's the following error in the container:
standard_init_linux.go:211: exec user process caused "exec format error"

## Steps to Reproduce

1. Use the example docker-compose file
2. Run it in docker

## Environment
**OS:**  Raspbian OS
**CPU architecture:**  arm64      
**How docker service was installed:** sudo apt-get install docker

## Command used to create docker container (run/create/compose/screenshot)

```yaml
version: "2.1"
services:
  calibre:
    image: linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - GUAC_USER=admin #optional
      - GUAC_PASS=900150983cd24fb0d6963f7d28e17f72 #optional
      - UMASK_SET=022 #optional
      - CLI_ARGS= #optional
    volumes:
      - /media/data/appdata/calibre:/config
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped
```
## Docker logs

```logs
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
standard_init_linux.go:211: exec user process caused "exec format error",
```
