### ISSUE TITLE
Latest Calibre version (5.0) can't start due to plugin compatibility(apparently)

### ISSUE THREAD

**Issue by emanueleleopardi** [linuxserver/docker-calibre#33]
When the latest docker image linuxserver/calibre:latest  the service doesn't come up with errors about Qt plugins
------------------------------

## Expected Behavior
The service should start as usual

## Current Behavior
The service doesn't start due to plugins compatibility ...?

## Steps to Reproduce
1. here's the docker compose I'm using:
```
version: "2"
services:
  calibre:
    image: linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - /media/Volume0/Ebooks:/Ebooks
      - /media/Volume1/Ebooks:/config
    ports:
      - 7070:8080
      - 7071:8081
      - 3389:3389
    restart: unless-stopped
```
2. `docker-compose up -d`

## Environment
**OS:**   Ubuntu 20.04 server
**CPU architecture:** x86_64
**How docker service was installed:**      
```
$ sudo apt-get update

$ sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

$ sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
$(lsb_release -cs) \
   stable"

$ sudo apt-get update
$ sudo apt-get install docker-ce docker-ce-cli containerd.io
```
## Command used to create docker container (run/create/compose/screenshot)
`docker-compose up -d`

## Docker logs
```

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
