### ISSUE TITLE
Installing latest image on OMV5 has issues, "s6-svwait: fatal: timed out"

### ISSUE THREAD

**Issue by adigandhi** [linuxserver/docker-calibre#36]
Hi,

 I am trying to install the latest image on my personal OMV5 server, using the Docker-compose file below. It gives me the error below  .I tried installing python, and python-xgd as per [this](https://github.com/linuxserver/docker-calibre/issues/10) post but that didn't help either. I suspect it might be something else.. I put those logs up as well. [https://pastebin.com/MjRRfeLZ](https://pastebin.com/MjRRfeLZ). But I thought not knowing much I should report on the original issue. 

Error before installing python or python-xgd manully 
```
rdpRRGetInfo:,
Obt-Message: Xinerama extension is not present on the server,
Openbox-Message: Unable to find a valid menu file "/var/lib/openbox/debian-menu.xml",
/usr/bin/env: 'python': No such file or directory,
rdpRRGetInfo:,
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-abc',
qt.qpa.xcb: QXcbConnection: XCB error: 148 (Unknown), sequence: 183, resource id: 0, major code: 140 (Unknown), minor code: 20,
s6-svwait: fatal: timed out,
```
Error after  installing python or python-xgd manully 
```
Obt-Message: Xinerama extension is not present on the server,
Openbox-Message: Unable to find a valid menu file "/var/lib/openbox/debian-menu.xml",
Connection failure: Connection refused,
pa_context_connect() failed: Connection refused,
rdpRRGetInfo:,
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-abc',
qt.qpa.xcb: QXcbConnection: XCB error: 148 (Unknown), sequence: 183, resource id: 0, major code: 140 (Unknown), minor code: 20,
s6-svwait: fatal: timed out,
```

My Docker-compose file:
```
---
version: "2.1"
services:
  calibre:
    image: linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=997
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /srv/dev-disk-by-label-MyMedia/CalibreLIbrary:/config
    ports:
      - 8082:8080
      - 8081:8081
    restart: unless-stopped
```

My OS:
Debian Buster  with OMV5 installed on top
arch   x86_64
build_version Linuxserver.io version:- v5.2.0-ls81 Build-date:- 2020-10-07T00:29:11-04:00
