### ISSUE TITLE
Calibre (and content server) not started on container startup anymore

### ISSUE THREAD

**Issue by danielwagn3r** [linuxserver/docker-calibre#44]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Calibre starts automatically in background when the container is starting, so that the calibre content server is running.

## Current Behavior
It seem's that at least since release v5.16.0-ls108 of the ghcr.io/linuxserver/calibre image calibre isn't started automatically in background when the container is starting up. After accessing the GUI on port 8080 calibre is starting and the content server on port 8081 is accessible, too.

Information about releases:

ghcr.io/linuxserver/calibre   acfebd2cb39d  --> doesn't work
ghcr.io/linuxserver/calibre   89cabd2c223d --> worked

## Steps to Reproduce

1. Start compose
2. Access calibre content server webui on port 8081
3. Request failes

## Environment
**OS:** Arch Linux
**CPU architecture:** x86_64
**How docker service was installed:** Arch Linux docker package from https://archlinux.org/packages/community/x86_64/docker/

## Command used to create docker container (run/create/compose/screenshot)
Using docker-compsoe with `docker-compose up -d` with the following compose file:

```
version: "3.7"

services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    environment:
      - PUID=968
      - PGID=968
      - TZ=Europe/Vienna
#      - GUAC_USER=calibre
#      - GUAC_PASS=secret
      - UMASK_SET=022 #optional
      - CLI_ARGS= #optional
    volumes:
      - ./data:/config
      - ./plugins:/plugins
      - ./import:/import
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped
  logs:
    image: bash
    depends_on:
      - calibre
    command: bash -c 'tail -F /config/.cache/calibre/*.txt'
    restart: unless-stopped
    volumes:
      - ./data:/config:ro
```
## Docker logs
See here https://gist.github.com/danielwagn3r/6a5030492fbd4ec92215fa174748d413
