### ISSUE TITLE
Support for physically connected USB devices

### ISSUE THREAD

**Issue by gritstub** [linuxserver/docker-calibre#58]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
- Allow a user to plug-in their Kindle or e-reader device via USB
- Allow a user to upload files directly to connected device

## Steps
- Start docker with: `--privileged -v /dev/bus/usb:/dev/bus/usb -v /var/run/dbus:/var/run/dbus`
- Allow the device to be seen by Calibre
- Open Preferences -> Miscellaneous -> Debug device detection

## Current Behavior
- Device is found, but complains that UDisks is not available on system
- called from calibre/devices/udisks.py

**Comment by aptalca** [comment]
Did you try mapping the specific device with something like `--device=/dev/ttyUSB0` ?

**Comment by computersandstuff** [comment]
I had the same issue. My host OS is Ubuntu 18.04, I look in `/dev` and cannot find any `ttyUSB*` devices. I also tried  mounting `/dev/bus/usb` as a volume with privileged, but no avail. If I shell into the calibre container I can use `lsusb `and `dsmesg` to check if my kindle is connected. It does list it as Amazon Kindle and even `lsblk` finds disk `/dev/sdc` which is the internal memory on my kindle. So the container is getting the USB devices, but calibre still doesn't detect them.

**Comment by computersandstuff** [comment]
After some more investigation I was able to fix a dbus error on my container by using `service dbus start` and installing udisks by doing `apt install udisks2` of course after doing `apt get update`. Now I get an error about not being able to open /dev/sdc1 which is the kindle.
It's actually an error produced by [this file](https://github.com/kovidgoyal/calibre/blob/master/src/calibre/devices/udisks.py) at line 93.

**Comment by Shourai** [comment]
It would great to have support for this.
I have tried mounting the disk into the container with/without privileged mode to no avail.
Calibre does see the kindle but it has the same error that @gritstub reported: `udisk mount call failed`

**Comment by emeybee** [comment]
I am having the same problems as the above...

**Comment by Shourai** [comment]
One way to get it working is to mount the kindle on the localhost and than map the volume to the container.

```
sudo mount /dev/sdc1 /mnt -o uid=1000,gid=1000,umask=0022
```
the options only work for FAT formatted filesystems, but it seems the kindle is formatted to FAT32.
We need the kindle to be mounted as the id the container will start on, in my case 1000.
When the kindle is mounted to your local system you can than map the volume with `-v /mnt:/mnt`.

an docker compose file that works:
```
---
version: "2.1"
services:
  calibre:
    image: lscr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - /path/to/calibre:/config
      - /mnt:/mnt
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped

```
