### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by gpapin** [linuxserver/docker-calibre#6]
Host OS : Ubuntu
Docker compose file used to setup the environment: 

```
version: "2"
services:
  calibre:
    image: linuxserver/calibre
    container_name: calibre
    environment:
      - PGID=100
      - PUID=1000
      - TZ=Europe/London
      #- GUAC_USER=abc #optional
      #- GUAC_PASS=900150983cd24fb0d6963f7d28e17f72 #optional
    volumes:
      - ./config:/config
      - /data/ebooks/:/data
    ports:
      - 4080:8080
      - 4081:8081
    restart: unless-stopped

  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibre-web:calibre #*optional* & **x86-64 only**
    volumes:
      - ./calibre-web:/config
      - /data/ebooks/data:/books
    ports:
      - 8083:8083
    restart: unless-stopped
```

Let's say I have a file named `été.pdf` in data:
On the host: `ls -al /data` returns:
```
-rw-rw-r-- 1 user user    0 Jul 15 20:39 été.pdf
```
Inside calibre container : `ls -al /data` returns:
```
-rw-rw-r-- 1 abc   1000    0 Jul 15 20:39 été.pdf
```

And yet in calibre when I try to import that file I get this : 
![Screenshot 2019-07-15 20 59 31](https://user-images.githubusercontent.com/3064311/61245049-8a830300-a743-11e9-95f1-1096155bd52b.png)

I'm not sure where the encoding issue comes from, if guacamole or calibre itself is doing it...
Any pointer would be appreciated thanks.
