### ISSUE TITLE
Blank Screen and unable to access GUI

### ISSUE THREAD

**Issue by adarshmathew** [linuxserver/docker-calibre#73]
## Expected Behavior

I should be able to go to `<SERVERURL>:8880`  and access Calibre.

## Current Behavior

Blank screen. Logs show multiple lines of 'rdpSaveScreen:'. 

## Steps to Reproduce

Unsure of how to reproduce this. I don't get this issue on a fresh service, but it invariably starts after a couple of days.
1. Run `docker-compose up`
2. Add books. (About 3k in my library right now)
3. Run the service for a couple of days

## Environment
**OS:** Ubuntu 20.04.3 LTS
**CPU architecture:** x86_64
**How docker service was installed:** Official docker repo

## Command used to create docker container (run/create/compose/screenshot)

```
version: "2.2"

services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - "TZ=America/New_York"
      - DISABLE_AUTH=TRUE
      # - PASSWORD= #optional
      # - CLI_ARGS= #optional
    volumes:
      - /home/user/server.config/calibre:/config
      - /home/user/local_media/Books/autoload:/data/autoload
    ports:
      - 8880:8080
      - 8081:8081
    restart: unless-stopped
```

## Docker logs

[Link to logs](https://gist.github.com/adarshmathew/6ec1995423c5947b872e9cfb2e7a4d0a)
