### ISSUE TITLE
python-qtwebengine in archlinuxarm docker image instead of python-qt5-webengine - dependency installed in wrong python version

### ISSUE THREAD

**Issue by prahal** [linuxserver/docker-calibre#86]
## Expected Behavior
ebook-viewer start when called

## Current Behavior
```
$ ebook-viewer 
Failed to import PyQt module: PyQt5.QtWebEngineCore with error: No module named 'PyQt5.QtWebEngineCore'
Traceback (most recent call last):
  File "/usr/sbin/ebook-viewer", line 21, in <module>
	sys.exit(ebook_viewer())
  File "/usr/lib/calibre/calibre/gui_launch.py", line 69, in ebook_viewer
	from calibre.gui2.viewer.main import main
  File "/usr/lib/calibre/calibre/gui2/viewer/main.py", line 9, in <module>
	from qt.webengine import QWebEngineUrlScheme
ImportError: cannot import name 'QWebEngineUrlScheme' from 'qt.webengine' (/usr/lib/calibre/qt/webengine.py)
```

## Steps to Reproduce
1. connect to the xrdp server
2. run xterm
3. enter ebook-viewer in it
4. press enter.
Or in calibre import a book and use calibre open with and choose ebook-viewer

NB: current image requires a qt5 upgrade with `sudo pacman -Syu --noconfirm` to workaround a glibc/qt5 migration breakage. This command also triggers a optional switch from python-pyqtwebengine to python-qt5-webengine:
```
:: Starting full system upgrade...
:: Replace python-pyqtwebengine with extra/python-pyqt5-webengine? [Y/n] 
resolving dependencies...
looking for conflicting packages...
```

NB2: https://github.com/linuxserver/docker-calibre/blob/arch/package_versions.txt tells that current packages are:
python-pyqt5-webengine 5.15.5-4
while in the docker image from docker hub it is:
local/python-pyqtwebengine 5.15.2-2 (pyqt5)

Both satisfy calibre dependency requirements. Maybe explicitly install python-pyqt5-webengine while installing calibre in the Dockerfile might avoid this discrepancy (which is proved at least on aarch64).

 

## Environment
**OS:** armbian
**CPU architecture:** arm64
**How docker service was installed:** from the official docker repo via portainer in a stack
```

## Command used to create docker container (run/create/compose/screenshot)
---
version: "2.1"
services:
  calibre:
    image: lscr.io/linuxserver/calibre:arch
    container_name: calibre
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/Paris
      - DOCKER_MODS=abws/mods:calibre-pacman-cache|abws/mods:calibre-log-openbox|abws/mods:calibre-readers|abws/mods:calibre-pycryptodome|abws/mods:calibre-filemanager
      - TMPDIR=$HOME/tmp
    volumes:
      - /srv/dev-disk-by-label-secure/appdata/docker/calibre:/config
      - /srv/dev-disk-by-label-store/media/calibre:/Calibre_Library
      - /srv/dev-disk-by-label-secure/ToCalibre:/config/ToCalibre
    ports:
      - 3389:3389
      - 8080:8080
      - 8081:8081
      - 9090:9090
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse:/dev/fuse"
```

## Docker logs
Not available
